version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./.docker/nginx/conf:/etc/nginx/conf.d
    restart:
      always
    depends_on:
      - php
      - database

  php:
    build:
      context: ./.docker/php
    #   image: php:8-fpm
    working_dir: /code
    depends_on:
      - database
    volumes:
      - ./:/code
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-schedule}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
